baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "My New Hugo Site"
languageCode = "en-us"
theme = "hugo-redlounge"

lightbox = true
nodate = true
disqusShortname = "dbparedes"


[params]
    sidebartitle = " David Paredes"
    sidebartagline = "Is super awesome"
    sidebarphoto = "/img/david.jpg"
    categoriescss = "/css/categories.css"

[[menu.main]]
    name = "Blog"
    url = "/post"

[[menu.main]]
    name = "Resume"
    url = "http://dbparedes.github.io/"

[[menu.social]]
    pre = "<i class='fa fa-twitter fa-lg'></i>"
    url = "http://www.twitter.com/dparedes28"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-github fa-lg'></i>"
    url = "http://www.github.com/dbparedes"
    identifier = "github"

[[menu.social]]
    pre = "<i class='fa fa-linkedin fa-lg'></i>"
    url = "http://www.linkedin.com/in/davidparedesm"
    identifier = "linkedin"


[[menu.footer]]
    name = "Blog"
    url = "/post"
